import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@/styles/globals.css"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
import { ClerkProvider } from '@clerk/nextjs'
import NavBar from '@/components/navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Prompts',
  description: 'Generated by create next app',
}
const queryClient = new QueryClient()
export default function RootLayout({
  count,
  children
}: {
  count: number
  children: React.ReactNode
}) {

  return (
    
      <ClerkProvider>
      <html lang="en">
        <body className="body">
          {/* <QueryClientProvider client={queryClient}> */}
          <NavBar />
          {children}
          {/* </QueryClientProvider> */}
        </body>
      </html>
    </ClerkProvider>

  )
}
